USER_NAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
SKILL_NAME_MAX_LENGTH = 124

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PAGE_SIZE = 12

SKILLS_AUTOCOMPLETE_LIMIT = 10