USER_NAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
SKILL_NAME_MAX_LENGTH = 124

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
)
PROJECT_STATUS_MAX_LENGTH = max(len(value) for value, _ in PROJECT_STATUS_CHOICES)

PAGE_SIZE = 12
